@IcMarkets.BlockchainHistory.Api_HostAddress = http://localhost:5190

### Get all available blockchain types
GET {{IcMarkets.BlockchainHistory.Api_HostAddress}}/api/BlockchainSnapshots/types
Accept: application/json

### Get blockchain snapshot history for a specific type
GET {{IcMarkets.BlockchainHistory.Api_HostAddress}}/api/BlockchainSnapshots/bitcoin?page=1&pageSize=50
Accept: application/json

### Get the latest blockchain snapshot for a specific type
GET {{IcMarkets.BlockchainHistory.Api_HostAddress}}/api/BlockchainSnapshots/bitcoin/latest
Accept: application/json

# Response
