version: '3.9'

services:
  db:
    image: postgres
    container_name: blockchain-postgres
    restart: always
    environment:
      POSTGRES_DB: blockchain_history
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: src/IcMarkets.BlockchainHistory.Api/Dockerfile
    container_name: blockchain-api
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: Host=db;Port=5432;Database=blockchain_history;Username=postgres;Password=mysecretpassword
    ports:
      - "8080:8080"

  worker:
    build:
      context: .
      dockerfile: src/IcMarkets.BlockchainHistory.WorkerService/Dockerfile
    container_name: blockchain-worker
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: Host=db;Port=5432;Database=blockchain_history;Username=postgres;Password=mysecretpassword

volumes:
  postgres_data: