// <auto-generated />
using System;
using IcMarkets.BlockchainHistory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IcMarkets.BlockchainHistory.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320114501_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IcMarkets.BlockchainHistory.Domain.Entities.BlockchainSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlockchainType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("blockchain_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("hash");

                    b.Property<long?>("Height")
                        .HasColumnType("bigint")
                        .HasColumnName("height");

                    b.Property<int?>("PeerCount")
                        .HasColumnType("integer")
                        .HasColumnName("peer_count");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_url");

                    b.Property<int?>("UnconfirmedCount")
                        .HasColumnType("integer")
                        .HasColumnName("unconfirmed_count");

                    b.HasKey("Id");

                    b.HasIndex("BlockchainType", "CreatedAt")
                        .HasDatabaseName("ix_blockchain_snapshots_type_created");

                    b.ToTable("blockchain_snapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
