// <auto-generated />
using System;
using IcMarkets.BlockchainHistory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IcMarkets.BlockchainHistory.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323143053_AddMissingBlockchainFields")]
    partial class AddMissingBlockchainFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IcMarkets.BlockchainHistory.Domain.Entities.BlockchainSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlockchainType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("blockchain_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("hash");

                    b.Property<long?>("Height")
                        .HasColumnType("bigint")
                        .HasColumnName("height");

                    b.Property<int?>("HighFeePerKb")
                        .HasColumnType("integer")
                        .HasColumnName("high_fee_per_kb");

                    b.Property<string>("LastForkHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("last_fork_hash");

                    b.Property<int?>("LastForkHeight")
                        .HasColumnType("integer")
                        .HasColumnName("last_fork_height");

                    b.Property<string>("LatestUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("latest_url");

                    b.Property<int?>("LowFeePerKb")
                        .HasColumnType("integer")
                        .HasColumnName("low_fee_per_kb");

                    b.Property<int?>("MediumFeePerKb")
                        .HasColumnType("integer")
                        .HasColumnName("medium_fee_per_kb");

                    b.Property<int?>("PeerCount")
                        .HasColumnType("integer")
                        .HasColumnName("peer_count");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("previous_hash");

                    b.Property<string>("PreviousUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("previous_url");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("time");

                    b.Property<int?>("UnconfirmedCount")
                        .HasColumnType("integer")
                        .HasColumnName("unconfirmed_count");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_blockchain_snapshots_hash")
                        .HasFilter("hash IS NOT NULL");

                    b.HasIndex("BlockchainType", "CreatedAt")
                        .HasDatabaseName("ix_blockchain_snapshots_type_created");

                    b.ToTable("blockchain_snapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
